apiVersion: v1
kind: Service
metadata:
  name: echoserver
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: echoserver
    component: echoserverapi
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.35
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: echoserver
    component: echoserverapi